/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/breadcrumb/index.vue')['default']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HorizontalScrollerMenu: typeof import('./src/components/sidebar/components/HorizontalScrollerMenu.vue')['default']
    Humburger: typeof import('./src/components/humburger/index.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    Logo: typeof import('./src/components/logo/index.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    NavBar: typeof import('./src/components/navbar/NavBar.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEl: typeof import('naive-ui')['NEl']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollerMenu: typeof import('./src/components/sidebar/components/ScrollerMenu.vue')['default']
    Setting: typeof import('./src/components/setting/index.vue')['default']
    SideBar: typeof import('./src/components/sidebar/SideBar.vue')['default']
    StyleExample: typeof import('./src/components/setting/components/StyleExample.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/index.vue')['default']
    TabSplitSideBar: typeof import('./src/components/sidebar/TabSplitSideBar.vue')['default']
    VAWAvatar: typeof import('./src/components/avatar/VAWAvatar.vue')['default']
  }
}
